name = "GN"
lname = "GN Build system"
grammar = "gn"
path_suffixes = ["gn", "gni"]
line_comments = ["% "]
brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false, not_in = [
    "string",
    "comment",
  ] },
]
tab_size = 2
