name = "GN"
grammar = "gn"
path_suffixes = ["gn", "gni"]
line_comments = ["# "]

[grammars.gn]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-gn"
rev = "bc06955bc1e3c9ff8e9b2b2a55b38b94da923c05"
